### ISSUE TITLE
Refresh Token rotation as MUST for public clients?

### ISSUE THREAD

**Issue by tlodderstedt** [aaronpk/oauth-v2-1#10]
Vittorio proposed to make this a MUST for SPAs only.

We need to think this through.

**Comment by aaronpk** [comment]
Does a client secret not already fall under the definition of a sender-constrained refresh token? I had actually already thought that a client secret would make refresh token rotation not necessary.

**Comment by tlodderstedt** [comment]
that's correct. It only makes sense for public clients, which don't have a way to use mTLS or DPoP for sender constraining.

**Comment by aaronpk** [comment]
This has been resolved:

```
When client authentication is not possible, the
authorization server SHOULD issue sender-constrained refresh tokens
or use refresh token rotation as described in (#refresh_token_protection).
```
