### ISSUE TITLE
authorization servers MUST support Private-Use URI Scheme Redirection?

### ISSUE THREAD

**Issue by jogu** [aaronpk/oauth-v2-1#106]
I'm potentially a little bit concerned by the wording here:

https://github.com/aaronpk/oauth-v2-1/blame/main/draft-ietf-oauth-v2-1.md#L3078-L3080

> To fully support native apps, authorization servers MUST offer
> at least the three redirect URI options described in the following
> subsections to native apps.

Admittedly this is very similar to the text in the [native apps BCP](https://datatracker.ietf.org/doc/html/rfc8252#section-7) (which I believe is where it came from). However having this text in a standard (rather than a BCP) seems problematic to me:

I think there are servers, particularly ones that aim for a higher-security profile (like OIDF's Financial-grade API), that would choose not to support private-use URI schemes (because of their generally poorer security compared to claimed `https` scheme redirects), and it seems such a server would not be OAuth 2.1 compliant.

**Comment by aaronpk** [comment]
From the IETF 113 minutes:

> we are going to re-order the list, claimed https URL first, loopback second, and private URI schemes. Remove the sentence for the mandatory-implementing all three
