### ISSUE TITLE
Clean up usage of the term "client identity"

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#18]
https://tools.ietf.org/html/draft-parecki-oauth-v2-1-03#section-2.3

> authorization server MUST NOT rely on credentialed
> client authentication for the purpose of identifying the client.

Most of the usage of the term is talking about identifying clients for the purposes of the consent screen. This usage seems to be different and is potentially confusing.

The concept of client identity needs to be defined somewhere.

The current text is hinting that there is something the AS should not be doing with credentialed clients that it might be doing if you're only looking for the presence of client authentication. That needs clarification.

**Comment by dickhardt** [comment]
Suggested text:

However, the authorization server MUST ONLY rely on information obtained from the client after being converted to a credentialed client.

**Comment by aaronpk** [comment]
Addressed by the removal of "credentialed client" in #123
