### ISSUE TITLE
Drop reference to "third-party" from abstract

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#19]
https://mailarchive.ietf.org/arch/msg/oauth/Ltm9TJ2mtfNAnHYhdV0-q5mEjdc/

**Comment by dickhardt** [comment]
The OAuth 2.1 authorization framework enables an
   application to obtain limited access to an HTTP service, either on
   behalf of a resource owner by orchestrating an approval interaction
   between the resource owner and the HTTP service, or by allowing the
   application to obtain access on its own behalf.  This
   specification replaces and obsoletes the OAuth 2.0 Authorization
   Framework described in RFC 6749 <https://tools.ietf.org/html/rfc6749>
   and the Bearer Token Usage in RFC 6750 <https://tools.ietf.org/html/rfc6750>
