### ISSUE TITLE
Why don't "always TLS" or similar

### ISSUE THREAD

**Issue by ioggstream** [aaronpk/oauth-v2-1#21]
# Question

iiuc the spec says that TLS:
- sometimes is MUST
- sometimes is SHOULD
- other parts say MUST always

why don't always TLS?

# Note

HTTP/3 aka QUIC may offer TLS-like mechanisms. We could ping the HTTP/3 workgroup and ask them if it is reasonable to make oauth2.1 specs independent from the adopted integrity layer.

**Comment by aaronpk** [comment]
I took a look through the doc and as far as I can tell the only instance of "SHOULD" is around redirect URLs. I'm going to close this in favor of keeping that discussion in #40
