### ISSUE TITLE
Clients as Resource Owners

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#27]
from Vittorio:

---

§1.3

I understand that we can’t really change this because we inherit from OAuth 2 but I’ll mention it anyway- modeling clients as ROs is problematic, as it doesn’t often match what happens in practice. A confidential client might batch-read a user’s inbox searching for ad words, but the resource owner remains the user.

I know we straighten things up in 1.3.2, but the positioning here is confusing.

Also: isn’t the refresh token grant a core-specified grant as well? I know I am nitpicking.

**Comment by dickhardt** [comment]
I don't understand the issue being brought up.

**Comment by aaronpk** [comment]
I think the mismatch is that "resource owner" is often thought of as an end user. The actual definition is "An entity capable of granting access to a protected resource", so I actually don't think there is a problem here other than it being slightly confusing. Under that definition, a client as a resource owner may already be capable of granting access to a resource that might be an actual user's data.
