### ISSUE TITLE
Clarify "authorization grant"

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#29]
From Justin:

---

§1.3: Having taught many OAuth 2 classes to hundreds of people over the years, I can say with confidence that this definition of “grant” as a credential has historically been problematic and confusing to most people. And in particular, it doesn’t even really apply to the client credentials flow listed here: there is not a separate "credential representing authorization", just the client’s own authentication. Suggest new text to more accurately reflect what a “grant” is in the OAuth reality:

> An authorization grant is a process by which a client obtains authorization from a resource owner to obtain an access token to act on that resource owner’s behalf. This specification defines...

Changing this would require a consensus call

**Comment by tlodderstedt** [comment]
most people refer to it as "flow" and there are flow not even involving a RO (like client credentials).

**Comment by dickhardt** [comment]
I don't think changing this will help -- and will likely cause lots of confusion. 
Myself, I think the larger issue is that we are conflating protocol roles with entities. The RO is not really part of the protocol, and the client can't own a resource.

**Comment by aaronpk** [comment]
Actually I'm now thinking maybe we should just drop section 1.3 entirely, since it's mainly a summary/duplicate of the new Section 4 "Grant Types". If anything, it could stay as just a summary of the flows and the header could change to "Summary of Grant Types" or something.
