### ISSUE TITLE
AS's confidence in the client's identity 

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#33]
From Vittorio:

---

Section 2.1 P4
> “Authorization servers SHOULD consider the level of confidence in a client's identity when deciding whether they allow such a client access to more critical functions, such as the Client Credentials grant type.” 

I don’t understand this sentence. Is the client credentials grant type a “more critical function”? Or is it a level of confidence? Either ways, I think it needs clarifying.

**Comment by dickhardt** [comment]
Agree it needs more clarification.

**Comment by aaronpk** [comment]
The "more critical functions" text was changed in #123
