### ISSUE TITLE
Authorization servers SHOULD use client authentication if possible

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#36]
From vittorio:

---

§[2.3](https://tools.ietf.org/html/draft-ietf-oauth-v2-1-00#section-2.3)

> Authorization servers SHOULD use client authentication if possible

That sounds vague. Shouldn’t it be mandatory for the AS to require client auth for the client types who have creds? “if possible” seem to open the possibility of circumstances where that’s not he case.

[§3.2.1](https://tools.ietf.org/html/draft-ietf-oauth-v2-1-00#section-3.2.1)
P1
That’s stricter than §2.3P3 – I think the language there should be tweaked to be coherent with the one here.

**Comment by aaronpk** [comment]
This came from the Security BCP. I think we should clarify this now that it's rolled into this draft. The Security BCP might also need to clarify the intent of this as well.

**Comment by tlodderstedt** [comment]
Can you point me to the respective text in the Security BCP?

**Comment by tlodderstedt** [comment]
I think 2.3 (and 9.1) is merely meant as general recommendation to use client authentication wherever possible. Stating that credentialed clients always need to authenticated seems obvious, but adding it does not hurt.

**Comment by dickhardt** [comment]
agreed

**Comment by aaronpk** [comment]
This was removed in draft -03

https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-03#section-2.4
