### ISSUE TITLE
clarify "identify the client"

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#37]
From vittorio:

---

https://tools.ietf.org/html/draft-ietf-oauth-v2-1-00#section-2.3

I think that this idea of identifying the client will need to be fleshed out more for people to fully understand it. Credentialed clients can prove that they are the same client instance across multiple transactions, which some might consider a weak form of identification. To rule that out, it has to be mentioned upfront IMO. If not here, in some of the considerations section… with a forward reference here.

**Comment by dickhardt** [comment]
I think a couple examples of how credentialed clients can be used, and should not be used will help.

**Comment by dickhardt** [comment]
Clients are confidential clients when the AS has prior knowledge of the client. Clients are credentialed clients when the AS only knows the clients credential.
