### ISSUE TITLE
The client MUST NOT use more than one authentication method

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#38]
from Vittorio:

---

> The client MUST NOT use more than one authentication method

Do we say why anywhere? If yes, we should reference it. If not, perhaps we should.

**Comment by tlodderstedt** [comment]
why MUST a client not use more than one authentication method? Why do we even need to talk about this in the spec?

**Comment by dickhardt** [comment]
Agree w/ Torsten

**Comment by aaronpk** [comment]
The question would be what happens if there are multiple authentication methods but they contain different credentials? Which would take priority etc

**Comment by tlodderstedt** [comment]
I think an AS should treat this as an error.

**Comment by dickhardt** [comment]
What about if the client is distributed, IE there are numerous servers that each have their own valid private key?

**Comment by tlodderstedt** [comment]
ok, I think I misread Aaron's statement. I don't see any issue with multiple different credentials.

1. Credentials of different kind (mechanism): the client is only allowed to authenticate in a certain request using one mechanism. An attempt to use e.g. mTLS for client authentication and BASIC is an error. 
2. Multiple credentials of same kind: If there are multiple instances of a client using the same mechanism but different credentials (e.g. different private keys), then this is possible as long as the client authentication mechanism supports it. mTLS does support the setup of clients with multiple certs.

**Comment by aaronpk** [comment]
The sentence quoted is actually this:

> The client MUST NOT use more than one authentication method **in each request**

So specifically about a single client request to the AS, it wouldn't make sense for it to have multiple authentication methods (e.g. mTLS as well as a client ID/secret)

**Comment by dickhardt** [comment]
to prevent a conflict of which authentication mechanism is authoritative for the request.
