### ISSUE TITLE
require HTTPS redirect URLs

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#40]
from vittorio:

---

https://tools.ietf.org/html/draft-ietf-oauth-v2-1-00#section-3.1.2.1

Personally, I would advocate for a MUST here. True, lots of people won’t comply at development time, but I think that’s OK as long as they do use TLS when going in production.

Also, SameSite changes are making the use of HTTPS at dev time more and more common. If OAuth2.1 is about picking the best of the security practices, this seems like a an obvious candidate.

**Comment by tlodderstedt** [comment]
+1 MUST - it makes sense, is simpler to explain than SHOULD and does not leave security holes

**Comment by ioggstream** [comment]
See #30 for a possible fix

**Comment by dickhardt** [comment]
+1

**Comment by aaronpk** [comment]
+1 with exceptions for localhost and custom URL schemes

**Comment by dickhardt** [comment]
Are we making recommendations on the loopback address? localhost vs 127.0.0.1 vs ::1?

**Comment by aaronpk** [comment]
Done in #98
