### ISSUE TITLE
require scope in the access token response

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#44]
from Justin:

---

[§3.3](https://tools.ietf.org/html/draft-ietf-oauth-v2-1-00#section-3.3): Can we start to mandate or at least recommend that scope is always returned and not just when it differs? Yes this is a breaking change for the AS but it doesn’t affect clients negatively, and it’s similar in requirement to doing exact redirect URI matching which is already done in this spec that OAuth 2.0 didn’t do.

**Comment by aaronpk** [comment]
I'm generally in favor of this, especially since a lot of ASs already behave this way anyway. I don't really see the benefit of allowing the AS to omit the scope values, and it's something I always have to explain to developers as a "well you might or might not get back the scope value, who knows"

**Comment by tlodderstedt** [comment]
that makes things simpler, I'm in favor of it. And it is not a breaking change from a client's perspective.

**Comment by dickhardt** [comment]
+1
