### ISSUE TITLE
Consider removing "flow" language

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#53]
From Justin's feedback:

> We should remove the “flow” based language throughout the document. This seems to have never quite gotten cleaned up previously.

**Comment by tlodderstedt** [comment]
+1
+1
+1
+1

**Comment by aaronpk** [comment]
The only inconsistency in the draft was the use of "client credentials flow", which is now resolved in 67cb9989140460fed39a40f75a4aa4929f88fbd6. The rest of the use of "flow" is consistent now.
