### ISSUE TITLE
Restrictions on authorization code content

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#56]
From Vittorio:

> Should we say that the code should be opaque to the client, to discourage the use of structured code templates that can be partially manufactured?

**Comment by aaronpk** [comment]
I agree, but I am not sure the best way or place to say this.

**Comment by tlodderstedt** [comment]
I suggest to add this to the definition of the code parameter (similar to access token opaqueness).

**Comment by dickhardt** [comment]
+1
