### ISSUE TITLE
Clarify extension grants

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#57]
From Vittorio:

> Section 4.3
> We mentioned extension grants in passing, but I don’t recall seeing a definition/description of their function in the context of the framework. Even a short sentence to that effect here would help, given that the section title names them explicitly. Also, stressing that the device flow is just one example and other extensions might differ (for example in their logic to establish whether an access token request is valid and authorized) would go a long way in helping the reader put this section in better focus.

**Comment by tlodderstedt** [comment]
+1 lets refactor the spec to make the extensibility a 1st class citizen

**Comment by dickhardt** [comment]
+1

**Comment by aaronpk** [comment]
Extension Grants in 4.4 next to the other grants makes this more clear now!

https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-03#section-4.4
