### ISSUE TITLE
Move refresh token section into the section with the other grants

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#61]
from Vittorio:

> §6: I wonder if now we should move this back to a “grant” type in §4. It originally was but the editor moved it out to its own section, but I have found that it confuses developers who are looking for it to have it on its own. Semantically it’s a grant (process to get an access token), but it feels like something “special” where it isn’t really.

**Comment by aaronpk** [comment]
I'm on the fence about this. Right now section 4 is about "obtaining authorization", so the refresh token grant doesn't really fit there. That said, there is a certain elegance in having all of the requests to the token endpoint described in the same section.

**Comment by tlodderstedt** [comment]
I fully agree with Vittorio. The spec currently is organized by use case, which results in the definition of the token endpoint scattered across sections 3-6 and even missing a clear request & response definition. 
I think the better way would be to have a base definition, which includes base parameters (grant_type), client authentication, and so on and additional sections covering code, client credentials and refresh token. 
We could even consider to put authz code in a separate section covering the authorisation endpoint as well. That would be a reasonable blueprint for extension grant types, e.g. assertion, device or CIBA.

Something like this: 

X. token endpoint
X+1 client credentials grant type
X+2 authorization code grant type
X+3 refresh token grant type

**Comment by aaronpk** [comment]
Done in #78 78
