### ISSUE TITLE
Incorporate changes for Errata ID 3446

### ISSUE THREAD

**Issue by adeinega** [aaronpk/oauth-v2-1#68]
https://www.rfc-editor.org/errata/eid3446

> Section 1 says:
> 
> o  Resource owners cannot revoke access to an individual third party
>    without revoking access to all third parties, and must do so by
>    changing the third party's password.
> It should say:
> 
> o  Resource owners cannot revoke access to an individual third party
>    without revoking access to all third parties, and must do so by
>    changing their password.
> Notes:
> 
> The text was originally "their" but changed to "the third party's" between the last draft and RFC.
> However, "their" means "resource owners'", not "the third party's".

**Comment by adeinega** [comment]
https://github.com/aaronpk/oauth-v2-1/pull/66

**Comment by aaronpk** [comment]
closed in #66
