### ISSUE TITLE
Use iss+sub, not just sub, to identify resource owner

### ISSUE THREAD

**Issue by manger** [aaronpk/oauth-v2-1#80]
The "Client Impersonating Resource Owner" section in "Security Considerations" says:

> "Resource servers may make access control decisions based on the identity of the resource owner as communicated in the sub claim"

However, the "sub" may only be "scoped to be locally unique in the context of the issuer" [RFC7519 JWT section 4.1.2 "sub" (Subject) claim]. So the identity of the resource owner is communicated by the combination of the "sub" and "iss" claims.

**Comment by tlodderstedt** [comment]
agree
