### ISSUE TITLE
Better term for a Bearer token that also has PoP

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#83]
From Vittorio:

> §7.2 “bearer tokens may be extended to include proof-of-possession  techniques by other specifications” sounds like an oxymoron. Wouldn’t PoP make the token no longer bearer by the very definition above? It looks like we might need a term for simply “token”.

**Comment by dickhardt** [comment]
bearer tokens may be enhanced with proof-of-possession specifications such as XXX to provider proof-of-possession characteristics

**Comment by tlodderstedt** [comment]
mTLS uses BEARER as token type
