### ISSUE TITLE
Should we tell RSs to ignore access tokens passed in the query string?

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/oauth-v2-1#85]
From Vittorio:

https://mailarchive.ietf.org/arch/msg/oauth/RP71xU8P4WLLIx0NcQMnw4gHScQ/

**Comment by dickhardt** [comment]
Same as #77

**Comment by dickhardt** [comment]
I'm wondering if we can be stronger and have it be an error. Ignore is likely the best approach.
